# Generated by Django 5.2.1 on 2026-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.CharField()),
                ('is_Premium', models.BooleanField(default=False)),
                ('SignUp_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
